# Generated by Django 5.1.7 on 2025-03-18 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_wallet_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
